name: cmake_run

on: [push, pull_request]

jobs:
  minimal-sample:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: prerequisites
        run: |
          sudo apt-get install -y --no-install-recommends \
            cmake \
            pandoc \
            texlive texlive-pictures texlive-latex-extra \
            lmodern

      - name: configure and build
        run: |
          mkdir build
          cmake -S . -B build
          cmake --build build --target minimal_slides.pdf minimal_script.pdf
