name: examples

on: [push, pull_request]

jobs:
  minimal-example:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: prerequisites
        run: |
          sudo apt-get install -y --no-install-recommends \
            cmake \
            pandoc \
            texlive texlive-pictures texlive-latex-extra \
            lmodern

      - name: configure and build
        run: |
          mkdir build
          cmake -S . -B build -DDOCMAKE_ENABLE_MINIMAL_EXAMPLE=ON
          cmake --build build

  maximal-example:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    env:
      DISPLAY: ":99"
    steps:
      - uses: actions/checkout@v2

      - name: "install and start xvfb as a workaround for drawio-desktop does not work without an X server"
        run: |
          sudo apt install -y --no-install-recommends desktop-file-utils xvfb
          Xvfb :99 &

      - name: "install ansible"
        run: |
          sudo apt-get install -y --no-install-recommends python3-pip
          sudo pip3 install ansible

      - name: "install prerequisites by using ansible-role-docmake"
        run: |
          git clone https://github.com/langchr86/ansible-role-docmake.git
          ./ansible-role-docmake/run_local.sh

      - name: configure and build
        run: |
          mkdir build
          cmake -S . -B build -DDOCMAKE_ENABLE_MAXIMAL_EXAMPLE=ON
          cmake --build build
